export type Company = {
  name: string
  industry: string
  role: string
  packageLPA: string
  minLPA: number
  maxLPA: number
  skills: string[]
  hiringProcess: string
  headquarters: string
  website: string
  highlights: string[]
  notSuitableFor: string[]
}

export const companies: Company[] = [
  {
    name: "Google",
    industry: "Technology",
    role: "Software Engineer (SWE) / STEP Intern → FT",
    packageLPA: "25–55 LPA",
    minLPA: 25,
    maxLPA: 55,
    skills: ["DSA", "Problem Solving", "Python/Java/C++", "System Design"],
    hiringProcess: "Online coding test → technical interviews → HR/team fit",
    headquarters: "Mountain View, USA (India: Bengaluru/Hyderabad/Gurugram)",
    website: "https://careers.google.com/",
    highlights: ["Strong coding interviews", "Great learning culture", "Product engineering roles"],
    notSuitableFor: ["Heavy mechanical core focus", "Pure civil/construction track", "Pure non-technical arts-only track"],
  },
  {
    name: "Microsoft",
    industry: "Technology",
    role: "Software Engineer",
    packageLPA: "20–45 LPA",
    minLPA: 20,
    maxLPA: 45,
    skills: ["DSA", "C#/Java", "Problem Solving", "CS fundamentals"],
    hiringProcess: "Online assessment → multiple technical rounds → HR",
    headquarters: "Redmond, USA (India: Hyderabad/Bengaluru/Noida)",
    website: "https://careers.microsoft.com/",
    highlights: ["Good fresher intake via campus + referrals", "Strong engineering tracks"],
    notSuitableFor: ["Pure civil/construction track", "Heavy mechanical core focus", "Arts-only (non-tech) career path"],
  },
  {
    name: "Amazon",
    industry: "Technology / E-commerce / Cloud",
    role: "SDE-1 (Software Development Engineer)",
    packageLPA: "18–45 LPA",
    minLPA: 18,
    maxLPA: 45,
    skills: ["DSA", "Java/Python", "OOP", "Problem Solving"],
    hiringProcess: "OA (coding + MCQ) → technical interviews → HR",
    headquarters: "Seattle, USA (India: Bengaluru/Hyderabad/Chennai/Pune)",
    website: "https://www.amazon.jobs/",
    highlights: ["Frequent campus hiring", "Strong backend roles", "Bar raiser interview"],
    notSuitableFor: ["Pure civil/construction track", "Arts-only (non-tech) career path", "Pure healthcare clinical track"],
  },
  {
    name: "Apple",
    industry: "Technology / Hardware",
    role: "Software Engineer / Hardware Validation (role varies)",
    packageLPA: "20–50 LPA",
    minLPA: 20,
    maxLPA: 50,
    skills: ["C/C++/Swift", "OS fundamentals", "Problem Solving", "Debugging"],
    hiringProcess: "Resume shortlisting → technical rounds → team fit",
    headquarters: "Cupertino, USA (India: Bengaluru/Hyderabad)",
    website: "https://jobs.apple.com/",
    highlights: ["Team-specific interviews", "Strong focus on fundamentals"],
    notSuitableFor: ["Pure civil/construction track", "Pure non-technical commerce-only path", "Arts-only (non-tech) career path"],
  },
  {
    name: "Meta",
    industry: "Technology",
    role: "Software Engineer (role varies by team)",
    packageLPA: "25–60 LPA",
    minLPA: 25,
    maxLPA: 60,
    skills: ["DSA", "C++/Python", "Systems", "Problem Solving"],
    hiringProcess: "Coding screening → onsite technical → behavioural",
    headquarters: "Menlo Park, USA (India: Bengaluru/Gurugram)",
    website: "https://www.metacareers.com/",
    highlights: ["High bar coding rounds", "Product + infrastructure roles"],
    notSuitableFor: ["Pure civil/construction track", "Heavy mechanical core focus", "Pure healthcare clinical track"],
  },
  {
    name: "Netflix",
    industry: "Technology / Media",
    role: "Software Engineer (rare fresher intake; mostly experienced)",
    packageLPA: "20–55 LPA",
    minLPA: 20,
    maxLPA: 55,
    skills: ["Backend fundamentals", "Distributed systems basics", "Problem Solving", "Java/Python"],
    hiringProcess: "Resume shortlisting → technical rounds → culture fit",
    headquarters: "Los Gatos, USA",
    website: "https://jobs.netflix.com/",
    highlights: ["Limited fresher roles", "High ownership expectations"],
    notSuitableFor: ["Pure civil/construction track", "Heavy mechanical core focus", "Pure healthcare clinical track"],
  },
  {
    name: "Tesla",
    industry: "Automotive / Energy / Technology",
    role: "Software Engineer / Embedded / Data (varies)",
    packageLPA: "15–45 LPA",
    minLPA: 15,
    maxLPA: 45,
    skills: ["C/C++", "Embedded basics", "Problem Solving", "Python"],
    hiringProcess: "Coding/technical screen → domain rounds → interviews",
    headquarters: "Austin, USA",
    website: "https://www.tesla.com/careers",
    highlights: ["Domain-heavy interviews", "Hardware + software roles"],
    notSuitableFor: ["Arts-only (non-tech) career path", "Pure finance/accounting-only path", "Pure non-technical commerce-only path"],
  },
  {
    name: "IBM",
    industry: "Technology / Consulting",
    role: "Associate System Engineer / Software Engineer",
    packageLPA: "6–18 LPA",
    minLPA: 6,
    maxLPA: 18,
    skills: ["Java/Python", "SQL", "Problem Solving", "Basics of Cloud"],
    hiringProcess: "Aptitude + coding → technical → HR",
    headquarters: "Armonk, USA (India: Bengaluru/Hyderabad/Pune)",
    website: "https://www.ibm.com/careers",
    highlights: ["Good fresher programs", "Enterprise tech exposure"],
    notSuitableFor: ["Pure civil/construction track", "Pure healthcare clinical track", "Arts-only (non-tech) career path"],
  },
  {
    name: "Oracle",
    industry: "Technology",
    role: "Software Engineer / Associate Consultant",
    packageLPA: "10–25 LPA",
    minLPA: 10,
    maxLPA: 25,
    skills: ["Java", "DBMS", "SQL", "DSA"],
    hiringProcess: "Online test → technical rounds → HR",
    headquarters: "Austin, USA (India: Bengaluru/Hyderabad)",
    website: "https://www.oracle.com/careers/",
    highlights: ["Database + cloud focus", "Strong CS fundamentals expected"],
    notSuitableFor: ["Pure civil/construction track", "Arts-only (non-tech) career path", "Pure healthcare clinical track"],
  },
  {
    name: "Adobe",
    industry: "Technology",
    role: "Software Engineer",
    packageLPA: "15–35 LPA",
    minLPA: 15,
    maxLPA: 35,
    skills: ["DSA", "Java/C++", "OOP", "Problem Solving"],
    hiringProcess: "Coding test → technical interviews → HR",
    headquarters: "San Jose, USA (India: Noida/Bengaluru)",
    website: "https://www.adobe.com/careers.html",
    highlights: ["Good campus hiring", "Product engineering roles"],
    notSuitableFor: ["Pure civil/construction track", "Heavy mechanical core focus", "Pure healthcare clinical track"],
  },
  {
    name: "Intel",
    industry: "Semiconductors",
    role: "Graduate Engineer Trainee / Validation Engineer",
    packageLPA: "10–25 LPA",
    minLPA: 10,
    maxLPA: 25,
    skills: ["C/C++", "Computer Architecture", "Digital basics", "Debugging"],
    hiringProcess: "Test → technical (domain) → HR",
    headquarters: "Santa Clara, USA (India: Bengaluru)",
    website: "https://jobs.intel.com/",
    highlights: ["Hardware fundamentals matter", "Verification/validation roles"],
    notSuitableFor: ["Pure civil/construction track", "Arts-only (non-tech) career path", "Pure healthcare clinical track"],
  },
  {
    name: "Cisco",
    industry: "Networking / Technology",
    role: "Software Engineer / Network Engineer (entry)",
    packageLPA: "12–28 LPA",
    minLPA: 12,
    maxLPA: 28,
    skills: ["Networking", "DSA", "Linux", "Python"],
    hiringProcess: "Online assessment → technical → managerial/HR",
    headquarters: "San Jose, USA (India: Bengaluru/Chennai)",
    website: "https://jobs.cisco.com/",
    highlights: ["Network + software roles", "Strong fundamentals needed"],
    notSuitableFor: ["Pure civil/construction track", "Arts-only (non-tech) career path", "Pure healthcare clinical track"],
  },
  {
    name: "Salesforce",
    industry: "Technology (SaaS)",
    role: "Associate Technical Consultant / Software Engineer",
    packageLPA: "12–30 LPA",
    minLPA: 12,
    maxLPA: 30,
    skills: ["OOP", "Java/JS", "Apex basics (optional)", "Problem Solving"],
    hiringProcess: "Assessment → technical rounds → HR",
    headquarters: "San Francisco, USA (India: Hyderabad/Bengaluru)",
    website: "https://www.salesforce.com/company/careers/",
    highlights: ["Consulting + product roles", "CRM/Cloud ecosystem"],
    notSuitableFor: ["Pure civil/construction track", "Heavy mechanical core focus", "Pure healthcare clinical track"],
  },
  {
    name: "Capgemini",
    industry: "IT Services / Consulting",
    role: "Associate Software Engineer",
    packageLPA: "4–8 LPA",
    minLPA: 4,
    maxLPA: 8,
    skills: ["Aptitude", "Java/Python basics", "Communication", "SQL basics"],
    hiringProcess: "Aptitude → technical → HR",
    headquarters: "Paris, France (India: multiple)",
    website: "https://www.capgemini.com/careers/",
    highlights: ["Frequent campus drives", "Large fresher intake"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "TCS",
    industry: "IT Services",
    role: "Assistant System Engineer (Ninja/Digital)",
    packageLPA: "3.5–9 LPA",
    minLPA: 3.5,
    maxLPA: 9,
    skills: ["Aptitude", "Programming basics", "Communication", "Problem Solving"],
    hiringProcess: "TCS NQT → technical interview → HR",
    headquarters: "Mumbai, India",
    website: "https://www.tcs.com/careers",
    highlights: ["NQT-based hiring", "Very frequent fresher recruitment"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "Infosys",
    industry: "IT Services",
    role: "System Engineer / Specialist Programmer",
    packageLPA: "3.6–12 LPA",
    minLPA: 3.6,
    maxLPA: 12,
    skills: ["Aptitude", "Java/Python", "DBMS basics", "Problem Solving"],
    hiringProcess: "Online test → technical → HR",
    headquarters: "Bengaluru, India",
    website: "https://www.infosys.com/careers.html",
    highlights: ["Large campus hiring", "Strong training programs"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "Wipro",
    industry: "IT Services",
    role: "Project Engineer / WILP (as applicable)",
    packageLPA: "3.5–7 LPA",
    minLPA: 3.5,
    maxLPA: 7,
    skills: ["Aptitude", "Programming basics", "Communication"],
    hiringProcess: "Online assessment → technical → HR",
    headquarters: "Bengaluru, India",
    website: "https://careers.wipro.com/",
    highlights: ["Frequent off-campus + campus drives", "Structured training"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "Accenture",
    industry: "Consulting / IT Services",
    role: "Associate Software Engineer / Analyst",
    packageLPA: "4.5–12 LPA",
    minLPA: 4.5,
    maxLPA: 12,
    skills: ["Aptitude", "Problem Solving", "Java/Python basics", "Communication"],
    hiringProcess: "Cognitive test → technical → HR",
    headquarters: "Dublin, Ireland (India: multiple)",
    website: "https://www.accenture.com/in-en/careers",
    highlights: ["Very frequent fresher hiring", "Multiple tech stacks/projects"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "HCL",
    industry: "IT Services",
    role: "Graduate Engineer Trainee",
    packageLPA: "3.5–8 LPA",
    minLPA: 3.5,
    maxLPA: 8,
    skills: ["Aptitude", "Java/Python basics", "OS/Networking basics"],
    hiringProcess: "Online test → technical → HR",
    headquarters: "Noida, India",
    website: "https://www.hcltech.com/careers",
    highlights: ["Good fresher intake", "Enterprise exposure"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "Cognizant",
    industry: "IT Services",
    role: "Programmer Analyst Trainee",
    packageLPA: "4–8 LPA",
    minLPA: 4,
    maxLPA: 8,
    skills: ["Aptitude", "Programming basics", "Communication", "SQL basics"],
    hiringProcess: "Online assessment → technical → HR",
    headquarters: "Teaneck, USA (India: Chennai/Bengaluru/Pune)",
    website: "https://careers.cognizant.com/",
    highlights: ["Frequent fresher drives", "Multiple domains/projects"],
    notSuitableFor: ["Pure healthcare clinical track", "Arts-only (non-tech) career path", "Heavy core-only (no IT) track"],
  },
  {
    name: "Deloitte",
    industry: "Consulting",
    role: "Analyst / Associate Consultant (Fresher)",
    packageLPA: "6–14 LPA",
    minLPA: 6,
    maxLPA: 14,
    skills: ["Aptitude", "Communication", "Excel/Analytics basics", "Problem Solving"],
    hiringProcess: "Aptitude/assessment → case/technical rounds → HR",
    headquarters: "London, UK (India: multiple)",
    website: "https://www2.deloitte.com/in/en/careers.html",
    highlights: ["Strong campus intake", "Consulting exposure", "Good learning curve"],
    notSuitableFor: ["Pure civil/construction track", "Pure healthcare clinical track", "Arts-only (non-tech) career path"],
  },
  {
    name: "JPMorgan Chase & Co.",
    industry: "Finance (Banking)",
    role: "Software Engineer (Fresher) / Analyst (varies)",
    packageLPA: "12–28 LPA",
    minLPA: 12,
    maxLPA: 28,
    skills: ["Java/Python", "DSA basics", "OOP", "Communication"],
    hiringProcess: "Online assessment → technical interviews → HR",
    headquarters: "New York, USA (India: Mumbai/Bengaluru/Hyderabad)",
    website: "https://careers.jpmorgan.com/",
    highlights: ["Strong tech roles in BFSI", "Good projects", "Stable career path"],
    notSuitableFor: ["Pure civil/construction track", "Arts-only (non-tech) career path", "Pure healthcare clinical track"],
  },
  {
    name: "EY (Ernst & Young)",
    industry: "Consulting / Audit",
    role: "Analyst / Associate (Fresher)",
    packageLPA: "5–12 LPA",
    minLPA: 5,
    maxLPA: 12,
    skills: ["Communication", "Excel", "Basic analytics", "Aptitude"],
    hiringProcess: "Assessment → interview rounds → HR",
    headquarters: "London, UK (India: multiple)",
    website: "https://www.ey.com/en_in/careers",
    highlights: ["Large fresher intake", "Multiple domains (audit/consulting)", "Good training"],
    notSuitableFor: ["Pure civil/construction track", "Pure healthcare clinical track", "Heavy core-only (no IT) track"],
  },
  {
    name: "KPMG",
    industry: "Consulting / Audit",
    role: "Analyst / Associate (Fresher)",
    packageLPA: "5–11 LPA",
    minLPA: 5,
    maxLPA: 11,
    skills: ["Communication", "Excel", "Analytical thinking", "Aptitude"],
    hiringProcess: "Assessment → interview rounds → HR",
    headquarters: "Amstelveen, Netherlands (India: multiple)",
    website: "https://kpmg.com/in/en/home/careers.html",
    highlights: ["Good for commerce/management grads", "Client exposure", "Structured learning"],
    notSuitableFor: ["Pure civil/construction track", "Pure healthcare clinical track", "Heavy core-only (no IT) track"],
  },
  {
    name: "Reliance Industries",
    industry: "Manufacturing / Energy / Retail",
    role: "Graduate Engineer Trainee / Analyst (varies)",
    packageLPA: "6–16 LPA",
    minLPA: 6,
    maxLPA: 16,
    skills: ["Core fundamentals", "Communication", "Problem Solving", "Excel basics"],
    hiringProcess: "Resume shortlisting → technical/domain rounds → HR",
    headquarters: "Mumbai, India",
    website: "https://careers.ril.com/",
    highlights: ["Strong core opportunities", "Large-scale operations", "Multiple business units"],
    notSuitableFor: ["Arts-only (non-tech) career path", "Pure software-only track (unless role is IT)", "Pure healthcare clinical track"],
  },
]